### ISSUE TITLE
add payment with creditcard

### ISSUE THREAD

**Issue by Vito8427** [xmohito/CarWise#1]
hello, wanting to add the payment of the machine by credit card or paypal, can it be done??
the email is not sent.

**Comment by xmohito** [comment]
Hi! The project is finished. It was created as my study project and didn't have a payment system in my project requirements, so I didn't add it.
There could be a problem with emailing because I have an account created on the mail service that blocks it after I send a few automatic emails to other accounts by SMTP server. You can solve this issue by editing code in Rent Controller and changing email account data.
